name: main

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Run ShellCheck
    - name: Run ShellCheck
      run: make shellcheck

    # Run Hadolint
    - name: Run Hadolint
      run: make hadolint

    # Set up Qemu for Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    # Set up Buildx for Docker
    - name: Set up Buildx for Docker
      uses: docker/setup-buildx-action@v1

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build image
    - name: Build image
      run: make build

    # Load image
    - name: Load image
      run: make load

    # Run trivy
    - name: Run trivy
      run: make trivy

    # Run dive
    - name: Run dive
      run: make dive

    # Publish image
    - name: Publish image
      run: make ci
